"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { ui } from "../ui";

type SharePayload = {
  title?: string;
  text?: string;
  url?: string;
};

function canWebShare() {
  return typeof navigator !== "undefined" && typeof navigator.share === "function";
}

function buildShareUrls(url: string, title: string) {
  const encodedUrl = encodeURIComponent(url);
  const encodedTitle = encodeURIComponent(title);

  return {
    email: `mailto:?subject=${encodedTitle}&body=${encodedTitle}%0A${encodedUrl}`,
  };
}

export default function ShareMenu({
  title = "BOT Holdings",
  text = "",
}: {
  title?: string;
  text?: string;
}) {
  const [copied, setCopied] = useState(false);
  const [showQr, setShowQr] = useState(false);
  const [url, setUrl] = useState("");

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setUrl(window.location.href);
  }, []);

  const shareUrls = useMemo(() => {
    if (!url) return null;
    return buildShareUrls(url, title);
  }, [url, title]);

  const qrUrl = useMemo(() => {
    if (!url) return "";
    // Uses a third-party QR generator endpoint.
    return `https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(
      url,
    )}`;
  }, [url]);

  async function onShare() {
    const payload: SharePayload = { title, text, url };
    if (canWebShare() && url) {
      try {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        await (navigator as any).share(payload);
        return;
      } catch {
        // user cancelled or share failed; fall back to copy
      }
    }
    if (url && navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1200);
    }
  }

  async function onCopy() {
    if (!url) return;
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1200);
    }
  }

  return (
    <div className={`${ui.card} p-4`}>
      <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
        <div className="text-sm text-[var(--muted)]">Share</div>
        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={onShare}
            className={`${ui.button} ${ui.buttonPrimary}`}
            disabled={!url}
          >
            Share
          </button>

          <button
            type="button"
            onClick={onCopy}
            className={`${ui.button} ${ui.buttonGhost}`}
            disabled={!url}
          >
            {copied ? "Copied" : "Copy link"}
          </button>

          <button
            type="button"
            onClick={() => setShowQr((v) => !v)}
            className={`${ui.button} ${ui.buttonGhost}`}
            disabled={!url}
          >
            QR
          </button>

          {shareUrls ? (
            <a className={`${ui.button} ${ui.buttonGhost}`} href={shareUrls.email}>
              Email
            </a>
          ) : null}
        </div>
      </div>

      {showQr && qrUrl ? (
        <div className="mt-4 flex flex-col items-center gap-3 border-t border-[var(--border)] pt-4">
          <Image
            src={qrUrl}
            alt="QR code"
            width={220}
            height={220}
            className="rounded-xl border border-[var(--border)] bg-white p-2"
          />
          <div className="flex flex-wrap items-center justify-center gap-2">
            <a className={`${ui.button} ${ui.buttonGhost}`} href={qrUrl} download>
              Download QR
            </a>
            <button
              type="button"
              onClick={() => setShowQr(false)}
              className={`${ui.button} ${ui.buttonGhost}`}
            >
              Close
            </button>
          </div>
          <div className="text-xs text-[var(--muted)]">
            QR is generated by a third-party service.
          </div>
        </div>
      ) : null}
    </div>
  );
}
